package org.damap.base.enums;

public enum EErrorCode {
  RE3DATA_NOT_FOUND,
  RE3DATA_NOT_AVAILABLE,
  RE3DATA_UNEXPECTED_ERROR,
  RE3DATA_RECOMMENDED_NOT_FOUND,
  RE3DATA_RECOMMENDED_NOT_AVAILABLE,
  RE3DATA_RECOMMENDED_UNEXPECTED_ERROR,
  ORCID_PERSON_NOT_FOUND,
  ORCID_NOT_AVAILABLE,
  ORCID_UNEXPECTED_ERROR,
  OPENAIRE_NOT_FOUND,
  OPENAIRE_NOT_AVAILABLE,
  OPENAIRE_UNEXPECTED_ERROR,
  GOTENBERG_NOT_AVAILABLE,
  GOTENBERG_UNEXPECTED_ERROR,
  PURE_NOT_FOUND,
  PURE_NOT_AVAILABLE,
  PURE_UNEXPECTED_ERROR,
  EVALUATION_NOT_AVAILABLE,
  EVALUATION_UNEXPECTED_ERROR
}
