damap:
  tenants:
    tenant-list: ['tenant_1', 'tenant_2']
    # these configs exactly mirror the damap.tenant-aware configs in application.yaml
    tenant-configs:
      tenant_1:
        title: Tenant 1 DAMAP Tool
        fields:
          ethical-report-enabled: false
        project-service: default
        elsevier-pure-description-classification: /dk/atira/pure/projectdescription
        elsevier-pure-contributor-role-classifications:
          - pure-role-uri: /dk/atira/pure/member
            contributor-role: PROJECT_MEMBER
        elsevier-pure-project-lead-role-classification: /dk/atira/pure/projectlead
        elsevier-pure-backend: http
        elsevier-pure-endpoint-url: "https://your-tenant1-pure-instance.elsevierpure.com/ws/api/"
        elsevier-pure-api-key: "your API key here"
        elsevier-pure-projects-file: "file:///path/to/projects.json"
        elsevier-pure-persons-file: "file:///path/to/persons.json"
        person-services:
          - display-text: 'ORCID'
            query-value: 'ORCID'
            class-name: 'org.damap.base.integration.orcid.ORCIDPersonServiceImpl'
          - display-text: 'University'
            query-value: 'UNIVERSITY'
            class-name: 'org.damap.base.integration.mock.MockUniversityPersonServiceImpl'
        evaluation-service-url: "https://ostrails-dmp-evaluation.arisnet.ac.at"
      tenant_2:
        title: Tenant 2 DAMAP Tool
        fields:
          ethical-report-enabled: false
        project-service: default
        elsevier-pure-description-classification: /dk/atira/pure/projectdescription
        elsevier-pure-contributor-role-classifications:
          - pure-role-uri: /dk/atira/pure/member
            contributor-role: PROJECT_MEMBER
        elsevier-pure-project-lead-role-classification: /dk/atira/pure/projectlead
        elsevier-pure-backend: http
        elsevier-pure-endpoint-url: "https://your-tenant2-pure-instance.elsevierpure.com/ws/api"
        elsevier-pure-api-key: "your API key here"
        elsevier-pure-projects-file: "file:///path/to/projects.json"
        elsevier-pure-persons-file: "file:///path/to/persons.json"
        person-services:
          - display-text: 'ORCID'
            query-value: 'ORCID'
            class-name: 'org.damap.base.integration.orcid.ORCIDPersonServiceImpl'
          - display-text: 'University'
            query-value: 'UNIVERSITY'
            class-name: 'org.damap.base.integration.mock.MockUniversityPersonServiceImpl'
        evaluation-service-url:

"%multitenant":
  quarkus:
    datasource:
      tenant_1:
        jdbc:
          url: jdbc:postgresql://damap-db:5432/tenant_1
          driver: ${quarkus.datasource.jdbc.driver}
        db-kind: ${quarkus.datasource.db-kind}
        username: ${quarkus.datasource.username}
        password: ${quarkus.datasource.password}
      tenant_2:
        jdbc:
          url: jdbc:postgresql://damap-db:5432/tenant_2
          driver: ${quarkus.datasource.jdbc.driver}
        db-kind: ${quarkus.datasource.db-kind}
        username: ${quarkus.datasource.username}
        password: ${quarkus.datasource.password}

    liquibase:
      tenant_1:
        migrate-at-start: true
        change-log: org/damap/base/db/changeLog-root.yaml
      tenant_2:
        migrate-at-start: true
        change-log: org/damap/base/db/changeLog-root.yaml