# This file defines auxiliary services for the production deployment of DAMAP.
# It is included in the main docker-compose.yaml file and should not be used on its own.

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    profiles:
      - with_keycloak
    command:
      - start
      - --hostname=https://${DAMAP_HOSTNAME?The DAMAP hostname for Keycloak is required}
      - --hostname-backchannel-dynamic
      - "true"
      - --http-enabled=true
      - --proxy-headers
      - xforwarded
      - --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_PASSWORD: "${KC_ADMIN_PASSWORD?The Keycloak admin password is required}"
      KC_BOOTSTRAP_ADMIN_USERNAME: "${KC_ADMIN_USERNAME?The Keycloak admin user is required}"
      KC_DB: postgres
      KC_DB_PASSWORD: "${KC_DB_PASSWORD?The Keycloak database password is required}"
      KC_DB_URL_DATABASE: "${KC_DB_DATABASE?The Keycloak database name is required}"
      KC_DB_URL_HOST: "${KC_DB_HOST:-keycloak-db}"
      KC_DB_URL_PORT: "${KC_DB_PORT:-5432}"
      KC_DB_USERNAME: "${KC_DB_USERNAME?The Keycloak database user is required}"
      KC_HOSTNAME: "${DAMAP_HOSTNAME?The DAMAP hostname for Keycloak is required}"
    configs:
      - source: damap-realm-import
        target: /opt/keycloak/data/import/damap-realm-import.json
    depends_on:
      keycloak-db:
        condition: service_healthy
        required: false # We don't require this since the DB only exists when the with_keycloak_db profile is enabled.
    networks:
      damap-internal:
        aliases:
          - keycloak
    healthcheck:
      test:
        - "CMD-SHELL"
        - "/bin/bash"
        - "-c"
        - |
          exec 3<>/dev/tcp/localhost/8080
          echo -e "GET /health/ready HTTP/1.1\nhost: localhost:8080\nconnection: close\n\n" >&3
          test "$(cat <&3 | grep -m 1 'HTTP/1.1 ')" = "HTTP/1.1 200 OK"
          exec 3<&-
          exec 3>&-
          exit $?

  keycloak-db:
    image: postgres:16
    profiles:
      - with_keycloak_db
    environment:
      PGDATA: /var/lib/postgresql/data/keycloak-db
      POSTGRES_USER: ${KC_DB_USERNAME?The Keycloak datasource username is required}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD?The Keycloak datasource password is required}
      POSTGRES_DB: ${KC_DB_DATABASE?The Keycloak database name is required}
    volumes:
      - ${KC_DB_DATA_HOST_PATH?Please specify a path for the Keycloak database data.}:/var/lib/postgresql/data
    networks:
      damap-internal:
        aliases:
          - keycloak-db
    healthcheck:
      test: [ "CMD", "/bin/sh", "-c", "/usr/bin/pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\"" ]
      interval: 5s
      start_period: 5s
      timeout: 15s
      retries: 5
