# This file contains a development setup of DAMAP as a Docker Compose file.
# NOTE: This is NOT intended for production use!

name: damap-dev

include:
  - docker-compose.auxiliary.yaml

services:
  backend:
    image: ghcr.io/damap-org/damap-backend:next
    # If testing a local backend build, Compose will build the image from this context 
    # and tag it as ghcr.io/damap-org/damap-backend:next, instead of pulling it.
    build:
      context: ../../
    restart: unless-stopped
    environment:
      # Optional database configuration values, can be overridden by environment variables.
      # This is useful in case the database host/port/name are different from the defaults.
      # Prefixed with DAMAP_ (not Quarkus-specific), used to build the full JDBC URL.
      DAMAP_DB_HOST: ${DAMAP_DB_HOST:-}
      DAMAP_DB_NAME: ${DAMAP_DB_NAME:-}
      DAMAP_DB_PORT: ${DAMAP_DB_PORT:-}
      QUARKUS_DATASOURCE_DB_KIND: ${DAMAP_DB_KIND:-postgresql}
      QUARKUS_DATASOURCE_PASSWORD: ${DAMAP_DB_PASSWORD:-pw4damap}
      QUARKUS_DATASOURCE_USERNAME: ${DAMAP_DB_USERNAME:-damap}
      QUARKUS_PROFILE: ${DAMAP_QUARKUS_PROFILE:-}
      QUARKUS_LOG_CATEGORY__IO_SMALLRYE_JWT_AUTH__LEVEL: DEBUG
      QUARKUS_LOG_CATEGORY__IO_SMALLRYE_JWT__LEVEL: DEBUG
      QUARKUS_LOG_CATEGORY__IO_QUARKUS__LEVEL: DEBUG
      QUARKUS_LOG_CATEGORY__ORG_ECLIPSE_MICROPROFILE__LEVEL: DEBUG
      QUARKUS_LOG_CATEGORY__ORG_JBOSS_RESTEASY_REACTIVE__LEVEL: DEBUG
    volumes:
      - ../tenants.yaml:/opt/damap/tenants.yaml:ro
    depends_on:
      postgres-db:
        condition: service_started
        required: false
      oracle-db:
        condition: service_started
        required: false
      keycloak:
        condition: service_healthy
      api-mock:
        condition: service_started
      gotenberg:
        condition: service_started
    networks:
      default:
        aliases:
          - damap-be
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/q/health/live" ]
      interval: 30s
      timeout: 15s
      retries: 5

  frontend:
    image: ghcr.io/damap-org/damap-frontend:next
    # If testing a local frontend build, Compose will build the image from this context 
    # and tag it as ghcr.io/damap-org/damap-frontend:next, instead of pulling it.
    # This assumes that the frontend is checked out alogside the backend.
    build:
      context: ../../../damap-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      default:
        aliases:
          - damap-fe

  nginx:
    image: nginx:1
    pull_policy: always
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - "8085:80"
    depends_on:
      - frontend
      - backend

  postgres-db:
    image: postgres:16
    pull_policy: always
    restart: unless-stopped
    profiles:
      - "" # default profile, active when no profile is specified
      - with_postgres
    environment:
      POSTGRES_USER: ${DAMAP_DB_USERNAME:-damap}
      POSTGRES_PASSWORD: ${DAMAP_DB_PASSWORD:-pw4damap}
      POSTGRES_DB: ${DAMAP_DB_NAME:-damap}
    ports:
      - "8088:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DAMAP_DB_USERNAME:-damap} -d ${DAMAP_DB_NAME:-damap}'" ]
      interval: 30s
      timeout: 15s
      retries: 5

  oracle-db:
    image: gvenzl/oracle-free:23-slim
    pull_policy: always
    restart: unless-stopped
    profiles:
      - with_oracle
    environment:
      APP_USER: ${DAMAP_DB_USERNAME:-damap}
      APP_USER_PASSWORD: ${DAMAP_DB_PASSWORD:-pw4damap}
      ORACLE_PASSWORD: ${DAMAP_DB_PASSWORD:-pw4damap}
    ports:
      - "8088:1521"
    volumes:
      - ora-data:/opt/oracle/oradata
    healthcheck:
      test: [ "CMD-SHELL", "healthcheck.sh" ]
      interval: 30s
      timeout: 15s
      retries: 5

volumes:
  pg-data:
  ora-data:
